name: Send Daily Lubrication Alerts

on:
  schedule:
    - cron: "30 4 * * *"   # 10 AM IST
  workflow_dispatch:

jobs:
  send-alert:
    runs-on: ubuntu-latest

    steps:
      - name: Send Outlook Mail
        run: |
          python - <<EOF
          import smtplib
          from email.mime.text import MIMEText
          import os

          subject = "Combo Line Lubrication Alert"

          body = """
          Daily Lubrication Reminder

          Please check lubrication dashboard.

          https://lubrication-app-3.onrender.com
          """

          msg = MIMEText(body)
          msg['Subject'] = subject
          msg['From'] = "ruchita.yerra@jindalstainless.com"
          msg['To'] = "ruchita.yerra@jindalstainless.com"

          server = smtplib.SMTP("smtp.office365.com", 587)
          server.starttls()

          server.login(
              "ruchita.yerra@jindalstainless.com",
              os.environ["OUTLOOK_PASSWORD"]
          )

          server.send_message(msg)
          server.quit()

          print("Mail sent successfully")
          EOF
        env:
          OUTLOOK_PASSWORD: ${{ secrets.OUTLOOK_PASSWORD }}
