name: Trigger Lubrication Alerts

on:
  schedule:
    - cron: '30 4 * * *'   # 10 AM IST
  workflow_dispatch:

jobs:
  trigger-alert:
    runs-on: ubuntu-latest

    steps:
      - name: Call alert endpoint
        run: |
          curl -L https://lubrication-app-3.onrender.com/run-alerts
