name: Outlook Lubrication Alert

on:
  workflow_dispatch:
  schedule:
    - cron: '30 4 * * *'   # 10 AM IST

jobs:
  send-mail:
    runs-on: ubuntu-latest

    steps:
      - name: Send email
        run: |
          python - <<EOF
          import smtplib
          from email.mime.text import MIMEText
          import os

          subject = "Combo Line Lubrication Alert"

          body = "Daily lubrication reminder. Check dashboard."

          msg = MIMEText(body)
          msg['Subject'] = subject
          msg['From'] = "ruchita.yerra@jindalstainless.com"
          msg['To'] = "ruchita.yerra@jindalstainless.com"

          server = smtplib.SMTP("smtp.office365.com", 587)
          server.starttls()

          server.login(
              "ruchita.yerra@jindalstainless.com",
              os.environ["OUTLOOK_PASSWORD"]
          )

          server.send_message(msg)
          server.quit()

          print("Mail sent")
          EOF
        env:
          OUTLOOK_PASSWORD: ${{ secrets.OUTLOOK_PASSWORD }}
